source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VISPER-CommandBus_Example' do
  pod 'VISPER-CommandBus', :path => '../'
end

target 'VISPER-CommandBus_Tests' do
  pod 'VISPER-CommandBus', :path => '../'

  
end
